owner: GR-webdev
repo: sarah-bot-status

sites:
  - name: Sarah Bot
    url: https://sarah-bot-q7vn.onrender.com/
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200

assignees:
  - GR-webdev

status-website:
  name: Sarah Bot Status
  introTitle: "🤖 Sarah Bot Uptime"
  introMessage: "Live monitoring dashboard"

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
